FROM tomcat:8.0
MAINTAINER Ram
RUN apt-get update && apt-get install -y curl
RUN apt-get install -y git-core && apt-get install -y wget
COPY index.html /usr/local/tomcat/webapps/ROOT/index.html
ADD https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war /usr/local/tomcat/webapps/sample.war
USER root
WORKDIR /usr/local/tomcat/
EXPOSE 8080
CMD ["catalina.sh","run"]
